# Generated by Django 4.2.3 on 2023-07-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarValueData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('trim', models.CharField(blank=True, max_length=50, null=True)),
                ('dealer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dealer_street', models.CharField(blank=True, max_length=200, null=True)),
                ('dealer_city', models.CharField(blank=True, max_length=50, null=True)),
                ('dealer_state', models.CharField(blank=True, max_length=50, null=True)),
                ('dealer_zip', models.CharField(blank=True, max_length=50, null=True)),
                ('listing_price', models.FloatField(blank=True, null=True)),
                ('listing_mileage', models.IntegerField(blank=True, null=True)),
                ('used', models.BooleanField(blank=True, null=True)),
                ('certified', models.BooleanField(blank=True, null=True)),
                ('style', models.CharField(blank=True, max_length=200, null=True)),
                ('driven_wheels', models.CharField(blank=True, max_length=200, null=True)),
                ('engine', models.CharField(blank=True, max_length=200, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=200, null=True)),
                ('exterior_color', models.CharField(blank=True, max_length=50, null=True)),
                ('interior_color', models.CharField(blank=True, max_length=50, null=True)),
                ('seller_website', models.CharField(blank=True, max_length=200, null=True)),
                ('first_seen_date', models.DateField(blank=True, null=True)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('dealer_vdp_last_seen_date', models.DateField(blank=True, null=True)),
                ('listing_status', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstimatedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_price', models.FloatField(blank=True, null=True)),
                ('listing_mileage', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
