# Generated by Django 4.2.3 on 2023-07-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0002_carvaluedata_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carvaluedata',
            name='vin',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
