# Generated by Django 4.2.3 on 2023-07-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0003_alter_carvaluedata_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carvaluedata',
            name='listing_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
