# Generated by Django 4.2.3 on 2023-07-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0004_alter_carvaluedata_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carvaluedata',
            name='listing_mileage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carvaluedata',
            name='listing_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimateddata',
            name='listing_mileage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
