# Generated by Django 4.2.3 on 2023-07-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0005_alter_carvaluedata_listing_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carvaluedata',
            name='dealer_city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carvaluedata',
            name='dealer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carvaluedata',
            name='dealer_state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carvaluedata',
            name='dealer_zip',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carvaluedata',
            name='exterior_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carvaluedata',
            name='interior_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carvaluedata',
            name='make',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carvaluedata',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carvaluedata',
            name='trim',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carvaluedata',
            name='vin',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='estimateddata',
            name='make',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='estimateddata',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
